version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: budgetbuddy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budgetBuddyDB
    ports:
      - "5432:5432"
    volumes:
      - budgetbuddy-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budgetBuddyDB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  budgetbuddy-pg-data: